# Treinamento com interface de alto nível

## Importação das bibliotecas

In [172]:
# http://pytorch.org/
from os.path import exists

import torch

In [173]:
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import Dataset, random_split
from torch.optim.lr_scheduler import StepLR

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split

# Dataset

In [174]:
#!/bin/bash
!curl -L -o /content/old-car-price-prediction.zip https://www.kaggle.com/api/v1/datasets/download/milanvaddoriya/old-car-price-prediction

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  105k  100  105k    0     0   155k      0 --:--:-- --:--:-- --:--:--  155k

In [175]:
!unzip -o /content/old-car-price-prediction.zip -d /content/old-car-price-prediction

Archive:  /content/old-car-price-prediction.zip
  inflating: /content/old-car-price-prediction/car_price.csv

In [176]:
old_car_prediction_csv = "/content/old-car-price-prediction/car_price.csv"

In [177]:
df = pd.read_csv(old_car_prediction_csv)
df.head()

,Unnamed: 0,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,0,Jeep Compass 2.0 Longitude Option BSIV,10.03 Lakh,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1,Renault Duster RXZ Turbo CVT,12.83 Lakh,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,2,Toyota Camry 2.5 G,16.40 Lakh,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,3,Honda Jazz VX CVT,7.77 Lakh,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,4,Volkswagen Polo 1.2 MPI Highline,5.15 Lakh,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5512 entries, 0 to 5511
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           5512 non-null   int64
 1   car_name             5512 non-null   object
 2   car_prices_in_rupee  5512 non-null   object
 3   kms_driven           5512 non-null   object
 4   fuel_type            5512 non-null   object
 5   transmission         5512 non-null   object
 6   ownership            5512 non-null   object
 7   manufacture          5512 non-null   int64
 8   engine               5512 non-null   object
 9   Seats                5512 non-null   object
dtypes: int64(2), object(8)
memory usage: 430.8+ KB

In [179]:
df.isnull().sum()

Unnamed: 0             0
car_name               0
car_prices_in_rupee    0
kms_driven             0
fuel_type              0
transmission           0
ownership              0
manufacture            0
engine                 0
Seats                  0
dtype: int64

In [180]:
df.duplicated().sum()

np.int64(0)

In [181]:
df.dtypes

Unnamed: 0              int64
car_name               object
car_prices_in_rupee    object
kms_driven             object
fuel_type              object
transmission           object
ownership              object
manufacture             int64
engine                 object
Seats                  object
dtype: object

In [182]:
df.nunique()

Unnamed: 0             5512
car_name               1896
car_prices_in_rupee    1300
kms_driven             2610
fuel_type                 5
transmission              2
ownership                 6
manufacture              26
engine                  139
Seats                     6
dtype: int64

In [183]:
df.describe()

        Unnamed: 0  manufacture
count  5512.000000  5512.000000
mean   2755.500000  2015.455552
std    1591.321673     3.927974
min       0.000000  1995.000000
25%    1377.750000  2013.000000
50%    2755.500000  2016.000000
75%    4133.250000  2018.000000
max    5511.000000  2022.000000

In [184]:
def car_model(x):
  return x[x.index(" ") + 1:]
def car_marca(x):
  return x[:x.index(" ")]
df["marca"] = df["car_name"].apply(car_marca)
df["car_name"] = df["car_name"].apply(car_model)

In [185]:
df.head()

,Unnamed: 0,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,marca
0,0,Compass 2.0 Longitude Option BSIV,10.03 Lakh,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats,Jeep
1,1,Duster RXZ Turbo CVT,12.83 Lakh,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats,Renault
2,2,Camry 2.5 G,16.40 Lakh,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats,Toyota
3,3,Jazz VX CVT,7.77 Lakh,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats,Honda
4,4,Polo 1.2 MPI Highline,5.15 Lakh,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats,Volkswagen

In [186]:
df[['price', 'multiply']] = df['car_prices_in_rupee'].str.split(' ', expand=True)
df.drop('car_prices_in_rupee', axis=1, inplace=True)

In [187]:
df.head()

,Unnamed: 0,car_name,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,marca,price,multiply
0,0,Compass 2.0 Longitude Option BSIV,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats,Jeep,10.03,Lakh
1,1,Duster RXZ Turbo CVT,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats,Renault,12.83,Lakh
2,2,Camry 2.5 G,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats,Toyota,16.40,Lakh
3,3,Jazz VX CVT,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats,Honda,7.77,Lakh
4,4,Polo 1.2 MPI Highline,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats,Volkswagen,5.15,Lakh

In [188]:
# Var: kms_driven - removing kms and convert to int
df['kms_driven'] = df['kms_driven'].str.replace(' kms', '')
df['kms_driven'] = df['kms_driven'].str.replace(',', '').astype('int')

# Var: manufacture -  convert to int
df['manufacture'] = df['manufacture'].astype('int')

# Var: engine - remove cc and convert to int
df['engine'] = df['engine'].str.replace(' cc', '').astype('int')

#Var: Seats - remove seats and convert to int
df['Seats'] = df['Seats'].str.replace(' Seats', '').astype('int')

# Var price - convert to float:
df['price'] = df['price'].str.replace(',', '.').astype('float')

In [189]:
df.head()

,Unnamed: 0,car_name,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,marca,price,multiply
0,0,Compass 2.0 Longitude Option BSIV,86226,Diesel,Manual,1st Owner,2017,1956,5,Jeep,10.03,Lakh
1,1,Duster RXZ Turbo CVT,13248,Petrol,Automatic,1st Owner,2021,1330,5,Renault,12.83,Lakh
2,2,Camry 2.5 G,60343,Petrol,Automatic,1st Owner,2016,2494,5,Toyota,16.40,Lakh
3,3,Jazz VX CVT,26696,Petrol,Automatic,1st Owner,2018,1199,5,Honda,7.77,Lakh
4,4,Polo 1.2 MPI Highline,69414,Petrol,Manual,1st Owner,2016,1199,5,Volkswagen,5.15,Lakh

In [190]:
df['price']=np.where(df['multiply'] == 'Crore',
                                           df['price'] * 100,
                                           df['price'])
df['price']=df['price']*100000

df.drop('multiply', axis=1, inplace=True)

In [191]:
df.head()

,Unnamed: 0,car_name,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,marca,price
0,0,Compass 2.0 Longitude Option BSIV,86226,Diesel,Manual,1st Owner,2017,1956,5,Jeep,1003000.0
1,1,Duster RXZ Turbo CVT,13248,Petrol,Automatic,1st Owner,2021,1330,5,Renault,1283000.0
2,2,Camry 2.5 G,60343,Petrol,Automatic,1st Owner,2016,2494,5,Toyota,1640000.0
3,3,Jazz VX CVT,26696,Petrol,Automatic,1st Owner,2018,1199,5,Honda,777000.0
4,4,Polo 1.2 MPI Highline,69414,Petrol,Manual,1st Owner,2016,1199,5,Volkswagen,515000.0

In [192]:
def owner(x):
  return x[:1]
df["ownership"] = df["ownership"].apply(owner)
df.head()

,Unnamed: 0,car_name,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,marca,price
0,0,Compass 2.0 Longitude Option BSIV,86226,Diesel,Manual,1,2017,1956,5,Jeep,1003000.0
1,1,Duster RXZ Turbo CVT,13248,Petrol,Automatic,1,2021,1330,5,Renault,1283000.0
2,2,Camry 2.5 G,60343,Petrol,Automatic,1,2016,2494,5,Toyota,1640000.0
3,3,Jazz VX CVT,26696,Petrol,Automatic,1,2018,1199,5,Honda,777000.0
4,4,Polo 1.2 MPI Highline,69414,Petrol,Manual,1,2016,1199,5,Volkswagen,515000.0

In [193]:
categorical_columns = ["car_name", "fuel_type", "transmission", "marca"]
for col in categorical_columns:
  print(f"Categoria na {col}: {df[col].unique()}")

Categoria na car_name: ['Compass 2.0 Longitude Option BSIV' 'Duster RXZ Turbo CVT' 'Camry 2.5 G'
 ... 'XC 90 D5 Momentum BSIV' 'E-Class E250 Edition E' 'M Series M4 Coupe']
Categoria na fuel_type: ['Diesel' 'Petrol' 'Cng' 'Electric' 'Lpg']
Categoria na transmission: ['Manual' 'Automatic']
Categoria na marca: ['Jeep' 'Renault' 'Toyota' 'Honda' 'Volkswagen' 'Maruti' 'Mahindra'
 'Hyundai' 'Nissan' 'Kia' 'MG' 'Tata' 'BMW' 'Mercedes-Benz' 'Datsun'
 'Volvo' 'Audi' 'Porsche' 'Ford' 'Chevrolet' 'Skoda' 'Lexus' 'Land' 'Mini'
 'Jaguar' 'Mitsubishi' 'Force' 'Premier' 'Fiat' 'Maserati' 'Bentley'
 'Isuzu']

In [194]:
df["ownership"] = df["ownership"].astype('int')

In [195]:
df.describe()

,Unnamed: 0,kms_driven,ownership,manufacture,engine,Seats,price
count,5512.000000,5512.000000,5512.000000,5512.000000,5512.000000,5512.000000,5.512000e+03
mean,2755.500000,63211.888062,1.421807,2015.455552,1532.299710,5.250726,1.329907e+06
std,1591.321673,41844.131167,0.703092,3.927974,579.210876,0.720075,2.192714e+06
min,0.000000,250.000000,0.000000,1995.000000,0.000000,2.000000,1.000000e+05
25%,1377.750000,33151.750000,1.000000,2013.000000,1197.000000,5.000000,3.300000e+05
50%,2755.500000,59000.000000,1.000000,2016.000000,1396.000000,5.000000,5.750000e+05
75%,4133.250000,84265.250000,2.000000,2018.000000,1950.000000,5.000000,1.149250e+06
max,5511.000000,560000.000000,5.000000,2022.000000,5950.000000,8.000000,1.920000e+07

In [196]:
car_name_encoded = LabelEncoder()
df["car_name"] = car_name_encoded.fit_transform(df["car_name"])

fuel_type_encoded = LabelEncoder()
df["fuel_type"] = fuel_type_encoded.fit_transform(df["fuel_type"])

transmission_encoded = LabelEncoder()
df["transmission"] = transmission_encoded.fit_transform(df["transmission"])

marca_encoded = LabelEncoder()
df["marca"] = marca_encoded.fit_transform(df["marca"])

In [197]:
df.head()

,Unnamed: 0,car_name,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,marca,price
0,0,426,86226,1,1,1,2017,1956,5,12,1003000.0
1,1,509,13248,4,0,1,2021,1330,5,26,1283000.0
2,2,290,60343,4,0,1,2016,2494,5,29,1640000.0
3,3,912,26696,4,0,1,2018,1199,5,8,777000.0
4,4,1095,69414,4,1,1,2016,1199,5,30,515000.0

In [198]:
standart_scaler = StandardScaler()
new_df = pd.DataFrame(standart_scaler.fit_transform(df), columns=df.columns)

In [199]:
new_df.head()

,Unnamed: 0,car_name,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats,marca,price
0,-1.731737,-0.915502,0.550046,-1.068243,0.625473,-0.599986,0.393228,0.731579,-0.348225,-0.425853,-0.149101
1,-1.731108,-0.771939,-1.194156,0.918538,-1.598790,-0.599986,1.411657,-0.349299,-0.348225,1.296126,-0.021394
2,-1.730480,-1.150738,-0.068568,0.918538,-1.598790,-0.599986,0.138621,1.660514,-0.348225,1.665122,0.141433
3,-1.729851,-0.074879,-0.872744,0.918538,-1.598790,-0.599986,0.647835,-0.575490,-0.348225,-0.917847,-0.252179
4,-1.729223,0.241652,0.148233,0.918538,0.625473,-0.599986,0.138621,-0.575490,-0.348225,1.788120,-0.371677

In [200]:
x = new_df[["car_name","kms_driven","fuel_type","transmission","ownership","manufacture","engine","Seats","marca"]]
y = new_df["price"]

In [201]:
y = y.values.reshape(-1, 1)
x = x.to_numpy()

In [202]:
x

array([[-0.91550178,  0.55004607, -1.0682431 , ...,  0.73157937,
        -0.34822548, -0.42585338],
       [-0.77193855, -1.19415602,  0.91853768, ..., -0.34929949,
        -0.34822548,  1.29612594],
       [-1.15073792, -0.06856752,  0.91853768, ...,  1.6605136 ,
        -0.34822548,  1.66512151],
       ...,
       [ 1.31059313,  0.64024611, -1.0682431 , ...,  2.11116757,
        -0.34822548, -0.5488519 ],
       [-1.60910245,  0.37734191, -1.0682431 , ...,  2.477216  ,
         1.04064487, -1.77883713],
       [-1.62985858, -0.50697223, -1.0682431 , ...,  0.7920119 ,
        -0.34822548, -1.77883713]])

In [203]:
y

array([[-0.14910131],
       [-0.02139412],
       [ 0.14143255],
       ...,
       [ 0.02056682],
       [ 0.75716366],
       [ 0.84838308]])

In [204]:
class OldCarDataset(Dataset):
  def __init__(self, x, y):
    super(OldCarDataset, self).__init__()
    if(len(x) != len(y)):
      raise ValueError("Size de X e Y não dão match!")
    self.x = torch.FloatTensor(x)
    self.y = torch.FloatTensor(y)
    self.x = torch.nan_to_num(self.x)
    self.y = torch.nan_to_num(self.y)

  def __getitem__(self, index):
     return self.x[index], self.y[index]

  def __len__(self):
    return len(self.x)

In [205]:
dataset = OldCarDataset(x, y)

In [206]:
train_data, val_data = random_split(dataset, [0.7, 0.3])

In [207]:
print(f"len treinamento: {len(train_data)}")

len treinamento: 3859

In [208]:
print(f"len val: {len(val_data)}")

len val: 1653

In [209]:
x.shape

(5512, 9)

## Criação da rede

In [210]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.layer1 = nn.Linear(9, 32)
        self.layer2 = nn.Linear(32, 64)
        self.layer2_1 = nn.Linear(64, 128)
        self.layer2_2 = nn.Linear(128, 64)
        self.layer3 = nn.Linear(64, 32)
        self.layer4 = nn.Linear(32, 1)

    def forward(self, x):
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        x = F.relu(x)
        x = self.layer2_1(x)
        x = F.relu(x)
        x = self.layer2_2(x)
        x = F.relu(x)
        x = self.layer3(x)
        x = F.relu(x)
        output = self.layer4(x)
        return output

model = Net()

In [211]:
model

Net(
  (layer1): Linear(in_features=9, out_features=32, bias=True)
  (layer2): Linear(in_features=32, out_features=64, bias=True)
  (layer2_1): Linear(in_features=64, out_features=128, bias=True)
  (layer2_2): Linear(in_features=128, out_features=64, bias=True)
  (layer3): Linear(in_features=64, out_features=32, bias=True)
  (layer4): Linear(in_features=32, out_features=1, bias=True)
)

## Treinamento

### Criando o objeto de treinamento

In [212]:
def train(log_interval, dry_run, model, device, train_loader, optimizer, epoch, criterion):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))
            if dry_run:
                break

In [213]:
def test(model, device, test_loader, criterion):
    model.eval()
    total_loss = 0
    total_samples = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            loss = criterion(output, target)
            total_loss += loss.item() * target.size(0)
            total_samples += target.size(0)
        mse = total_loss / total_samples
        print(f"\nMSE validation: {mse:.4f}\n")
    return mse

## Avaliação

In [217]:
use_cuda = torch.cuda.is_available()

torch.manual_seed(1111)

device = torch.device("cuda" if use_cuda else "cpu")

train_kwargs = {'batch_size': 300}
test_kwargs = {'batch_size': 1000}
if use_cuda:
    cuda_kwargs = {'num_workers': 1,
                    'pin_memory': True,
                    'shuffle': True}
    train_kwargs.update(cuda_kwargs)
    test_kwargs.update(cuda_kwargs)

train_loader = torch.utils.data.DataLoader(train_data,**train_kwargs)
test_loader = torch.utils.data.DataLoader(val_data, **test_kwargs)
model = Net().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)
criterion = nn.MSELoss()
best_loss = test(model, device, test_loader, criterion)
epochs = 300
# scheduler = StepLR(optimizer, step_size=1, gamma=0.7)

for epoch in range(1, epochs + 1):
    train(10, False, model, device, train_loader, optimizer, epoch, criterion)
    loss = test(model, device, test_loader, criterion)
    if (loss < best_loss):
      best_loss = loss
      torch.save(model.state_dict(), "old_car_nn.pt")

MSE validation: 1.1375

Train Epoch: 1 [0/3859 (0%)]	Loss: 1.203932
Train Epoch: 1 [3000/3859 (77%)]	Loss: 0.801526

MSE validation: 1.1370

Train Epoch: 2 [0/3859 (0%)]	Loss: 0.886171
Train Epoch: 2 [3000/3859 (77%)]	Loss: 0.703734

MSE validation: 1.1367

Train Epoch: 3 [0/3859 (0%)]	Loss: 0.775273
Train Epoch: 3 [3000/3859 (77%)]	Loss: 0.773928

MSE validation: 1.1365

Train Epoch: 4 [0/3859 (0%)]	Loss: 0.819317
Train Epoch: 4 [3000/3859 (77%)]	Loss: 0.654363

MSE validation: 1.1363

Train Epoch: 5 [0/3859 (0%)]	Loss: 1.001948
Train Epoch: 5 [3000/3859 (77%)]	Loss: 0.715161

MSE validation: 1.1362

Train Epoch: 6 [0/3859 (0%)]	Loss: 0.879718
Train Epoch: 6 [3000/3859 (77%)]	Loss: 0.565711

MSE validation: 1.1360

Train Epoch: 7 [0/3859 (0%)]	Loss: 1.036060
Train Epoch: 7 [3000/3859 (77%)]	Loss: 0.747147

MSE validation: 1.1358

Train Epoch: 8 [0/3859 (0%)]	Loss: 0.575030
Train Epoch: 8 [3000/3859 (77%)]	Loss: 0.780354

MSE validation: 1.1356

Train Epoch: 9 [0/3859 (0%)]	Loss: 0.777102
Train Epoch: 9 [3000/3859 (77%)]	Loss: 1.350155

MSE validation: 1.1354

Train Epoch: 10 [0/3859 (0%)]	Loss: 1.048365
Train Epoch: 10 [3000/3859 (77%)]	Loss: 0.941940

MSE validation: 1.1352

Train Epoch: 11 [0/3859 (0%)]	Loss: 0.780459
Train Epoch: 11 [3000/3859 (77%)]	Loss: 1.196688

MSE validation: 1.1350

Train Epoch: 12 [0/3859 (0%)]	Loss: 0.420631
Train Epoch: 12 [3000/3859 (77%)]	Loss: 1.400848

MSE validation: 1.1347

Train Epoch: 13 [0/3859 (0%)]	Loss: 1.198094
Train Epoch: 13 [3000/3859 (77%)]	Loss: 0.620361

MSE validation: 1.1346

Train Epoch: 14 [0/3859 (0%)]	Loss: 0.595077
Train Epoch: 14 [3000/3859 (77%)]	Loss: 1.154879

MSE validation: 1.1343

Train Epoch: 15 [0/3859 (0%)]	Loss: 0.805916
Train Epoch: 15 [3000/3859 (77%)]	Loss: 0.920434

MSE validation: 1.1340

Train Epoch: 16 [0/3859 (0%)]	Loss: 1.357695
Train Epoch: 16 [3000/3859 (77%)]	Loss: 0.954785

MSE validation: 1.1338

Train Epoch: 17 [0/3859 (0%)]	Loss: 1.243161
Train Epoch: 17 [3000/3859 (77%)]	Loss: 1.194096

MSE validation: 1.1335

Train Epoch: 18 [0/3859 (0%)]	Loss: 0.804917
Train Epoch: 18 [3000/3859 (77%)]	Loss: 0.772948

MSE validation: 1.1332

Train Epoch: 19 [0/3859 (0%)]	Loss: 0.812025
Train Epoch: 19 [3000/3859 (77%)]	Loss: 0.881891

MSE validation: 1.1329

Train Epoch: 20 [0/3859 (0%)]	Loss: 0.857176
Train Epoch: 20 [3000/3859 (77%)]	Loss: 1.041990

MSE validation: 1.1326

Train Epoch: 21 [0/3859 (0%)]	Loss: 0.803722
Train Epoch: 21 [3000/3859 (77%)]	Loss: 1.013355

MSE validation: 1.1322

Train Epoch: 22 [0/3859 (0%)]	Loss: 1.146764
Train Epoch: 22 [3000/3859 (77%)]	Loss: 0.679352

MSE validation: 1.1318

Train Epoch: 23 [0/3859 (0%)]	Loss: 0.780810
Train Epoch: 23 [3000/3859 (77%)]	Loss: 0.523435

MSE validation: 1.1314

Train Epoch: 24 [0/3859 (0%)]	Loss: 0.880974
Train Epoch: 24 [3000/3859 (77%)]	Loss: 1.003299

MSE validation: 1.1310

Train Epoch: 25 [0/3859 (0%)]	Loss: 0.868370
Train Epoch: 25 [3000/3859 (77%)]	Loss: 1.364087

MSE validation: 1.1305

Train Epoch: 26 [0/3859 (0%)]	Loss: 0.771169
Train Epoch: 26 [3000/3859 (77%)]	Loss: 0.792610

MSE validation: 1.1300

Train Epoch: 27 [0/3859 (0%)]	Loss: 0.862479
Train Epoch: 27 [3000/3859 (77%)]	Loss: 0.850009

MSE validation: 1.1296

Train Epoch: 28 [0/3859 (0%)]	Loss: 1.214933
Train Epoch: 28 [3000/3859 (77%)]	Loss: 0.766323

MSE validation: 1.1291

Train Epoch: 29 [0/3859 (0%)]	Loss: 1.112016
Train Epoch: 29 [3000/3859 (77%)]	Loss: 0.788232

MSE validation: 1.1286

Train Epoch: 30 [0/3859 (0%)]	Loss: 0.988916
Train Epoch: 30 [3000/3859 (77%)]	Loss: 0.967417

MSE validation: 1.1280

Train Epoch: 31 [0/3859 (0%)]	Loss: 1.064130
Train Epoch: 31 [3000/3859 (77%)]	Loss: 0.829599

MSE validation: 1.1274

Train Epoch: 32 [0/3859 (0%)]	Loss: 0.604244
Train Epoch: 32 [3000/3859 (77%)]	Loss: 0.603334

MSE validation: 1.1267

Train Epoch: 33 [0/3859 (0%)]	Loss: 0.784944
Train Epoch: 33 [3000/3859 (77%)]	Loss: 0.847828

MSE validation: 1.1259

Train Epoch: 34 [0/3859 (0%)]	Loss: 0.518342
Train Epoch: 34 [3000/3859 (77%)]	Loss: 0.936504

MSE validation: 1.1252

Train Epoch: 35 [0/3859 (0%)]	Loss: 0.654412
Train Epoch: 35 [3000/3859 (77%)]	Loss: 0.530118

MSE validation: 1.1244

Train Epoch: 36 [0/3859 (0%)]	Loss: 1.233527
Train Epoch: 36 [3000/3859 (77%)]	Loss: 0.832919

MSE validation: 1.1236

Train Epoch: 37 [0/3859 (0%)]	Loss: 1.216717
Train Epoch: 37 [3000/3859 (77%)]	Loss: 1.037667

MSE validation: 1.1226

Train Epoch: 38 [0/3859 (0%)]	Loss: 0.809967
Train Epoch: 38 [3000/3859 (77%)]	Loss: 0.925082

MSE validation: 1.1216

Train Epoch: 39 [0/3859 (0%)]	Loss: 1.095279
Train Epoch: 39 [3000/3859 (77%)]	Loss: 0.605999

MSE validation: 1.1206

Train Epoch: 40 [0/3859 (0%)]	Loss: 1.509127
Train Epoch: 40 [3000/3859 (77%)]	Loss: 0.948513

MSE validation: 1.1194

Train Epoch: 41 [0/3859 (0%)]	Loss: 1.705215
Train Epoch: 41 [3000/3859 (77%)]	Loss: 0.726333

MSE validation: 1.1182

Train Epoch: 42 [0/3859 (0%)]	Loss: 1.053151
Train Epoch: 42 [3000/3859 (77%)]	Loss: 1.160347

MSE validation: 1.1168

Train Epoch: 43 [0/3859 (0%)]	Loss: 1.070610
Train Epoch: 43 [3000/3859 (77%)]	Loss: 0.542337

MSE validation: 1.1153

Train Epoch: 44 [0/3859 (0%)]	Loss: 0.701484
Train Epoch: 44 [3000/3859 (77%)]	Loss: 0.669352

MSE validation: 1.1137

Train Epoch: 45 [0/3859 (0%)]	Loss: 0.687802
Train Epoch: 45 [3000/3859 (77%)]	Loss: 0.941274

MSE validation: 1.1119

Train Epoch: 46 [0/3859 (0%)]	Loss: 0.997991
Train Epoch: 46 [3000/3859 (77%)]	Loss: 1.252127

MSE validation: 1.1100

Train Epoch: 47 [0/3859 (0%)]	Loss: 1.347545
Train Epoch: 47 [3000/3859 (77%)]	Loss: 0.871865

MSE validation: 1.1080

Train Epoch: 48 [0/3859 (0%)]	Loss: 0.648951
Train Epoch: 48 [3000/3859 (77%)]	Loss: 1.345530

MSE validation: 1.1055

Train Epoch: 49 [0/3859 (0%)]	Loss: 0.737787
Train Epoch: 49 [3000/3859 (77%)]	Loss: 0.573027

MSE validation: 1.1031

Train Epoch: 50 [0/3859 (0%)]	Loss: 1.352820
Train Epoch: 50 [3000/3859 (77%)]	Loss: 0.876664

MSE validation: 1.1003

Train Epoch: 51 [0/3859 (0%)]	Loss: 1.172865
Train Epoch: 51 [3000/3859 (77%)]	Loss: 0.868106

MSE validation: 1.0973

Train Epoch: 52 [0/3859 (0%)]	Loss: 1.073987
Train Epoch: 52 [3000/3859 (77%)]	Loss: 0.692373

MSE validation: 1.0940

Train Epoch: 53 [0/3859 (0%)]	Loss: 0.966479
Train Epoch: 53 [3000/3859 (77%)]	Loss: 0.892342

MSE validation: 1.0904

Train Epoch: 54 [0/3859 (0%)]	Loss: 1.108820
Train Epoch: 54 [3000/3859 (77%)]	Loss: 0.614597

MSE validation: 1.0864

Train Epoch: 55 [0/3859 (0%)]	Loss: 0.724536
Train Epoch: 55 [3000/3859 (77%)]	Loss: 0.951592

MSE validation: 1.0819

Train Epoch: 56 [0/3859 (0%)]	Loss: 1.171812
Train Epoch: 56 [3000/3859 (77%)]	Loss: 1.128189

MSE validation: 1.0771

Train Epoch: 57 [0/3859 (0%)]	Loss: 0.671452
Train Epoch: 57 [3000/3859 (77%)]	Loss: 0.693515

MSE validation: 1.0717

Train Epoch: 58 [0/3859 (0%)]	Loss: 1.002685
Train Epoch: 58 [3000/3859 (77%)]	Loss: 0.824330

MSE validation: 1.0658

Train Epoch: 59 [0/3859 (0%)]	Loss: 0.692799
Train Epoch: 59 [3000/3859 (77%)]	Loss: 0.727385

MSE validation: 1.0591

Train Epoch: 60 [0/3859 (0%)]	Loss: 0.685581
Train Epoch: 60 [3000/3859 (77%)]	Loss: 0.987937

MSE validation: 1.0519

Train Epoch: 61 [0/3859 (0%)]	Loss: 0.860990
Train Epoch: 61 [3000/3859 (77%)]	Loss: 0.489452

MSE validation: 1.0441

Train Epoch: 62 [0/3859 (0%)]	Loss: 0.610598
Train Epoch: 62 [3000/3859 (77%)]	Loss: 0.972186

MSE validation: 1.0355

Train Epoch: 63 [0/3859 (0%)]	Loss: 0.871190
Train Epoch: 63 [3000/3859 (77%)]	Loss: 0.737131

MSE validation: 1.0258

Train Epoch: 64 [0/3859 (0%)]	Loss: 1.122199
Train Epoch: 64 [3000/3859 (77%)]	Loss: 0.857315

MSE validation: 1.0153

Train Epoch: 65 [0/3859 (0%)]	Loss: 0.847600
Train Epoch: 65 [3000/3859 (77%)]	Loss: 1.367325

MSE validation: 1.0038

Train Epoch: 66 [0/3859 (0%)]	Loss: 0.653666
Train Epoch: 66 [3000/3859 (77%)]	Loss: 0.561390

MSE validation: 0.9916

Train Epoch: 67 [0/3859 (0%)]	Loss: 1.135992
Train Epoch: 67 [3000/3859 (77%)]	Loss: 0.673420

MSE validation: 0.9786

Train Epoch: 68 [0/3859 (0%)]	Loss: 0.372989
Train Epoch: 68 [3000/3859 (77%)]	Loss: 0.629574

MSE validation: 0.9652

Train Epoch: 69 [0/3859 (0%)]	Loss: 0.768388
Train Epoch: 69 [3000/3859 (77%)]	Loss: 0.620161

MSE validation: 0.9518

Train Epoch: 70 [0/3859 (0%)]	Loss: 0.595976
Train Epoch: 70 [3000/3859 (77%)]	Loss: 0.760748

MSE validation: 0.9384

Train Epoch: 71 [0/3859 (0%)]	Loss: 0.698391
Train Epoch: 71 [3000/3859 (77%)]	Loss: 0.605247

MSE validation: 0.9260

Train Epoch: 72 [0/3859 (0%)]	Loss: 0.566988
Train Epoch: 72 [3000/3859 (77%)]	Loss: 0.711737

MSE validation: 0.9137

Train Epoch: 73 [0/3859 (0%)]	Loss: 0.529163
Train Epoch: 73 [3000/3859 (77%)]	Loss: 0.919938

MSE validation: 0.9024

Train Epoch: 74 [0/3859 (0%)]	Loss: 0.798451
Train Epoch: 74 [3000/3859 (77%)]	Loss: 0.593268

MSE validation: 0.8925

Train Epoch: 75 [0/3859 (0%)]	Loss: 1.014144
Train Epoch: 75 [3000/3859 (77%)]	Loss: 1.131371

MSE validation: 0.8837

Train Epoch: 76 [0/3859 (0%)]	Loss: 0.548332
Train Epoch: 76 [3000/3859 (77%)]	Loss: 0.681977

MSE validation: 0.8761

Train Epoch: 77 [0/3859 (0%)]	Loss: 0.610878
Train Epoch: 77 [3000/3859 (77%)]	Loss: 1.076282

MSE validation: 0.8691

Train Epoch: 78 [0/3859 (0%)]	Loss: 0.733210
Train Epoch: 78 [3000/3859 (77%)]	Loss: 0.633870

MSE validation: 0.8630

Train Epoch: 79 [0/3859 (0%)]	Loss: 0.915966
Train Epoch: 79 [3000/3859 (77%)]	Loss: 0.471698

MSE validation: 0.8571

Train Epoch: 80 [0/3859 (0%)]	Loss: 0.855345
Train Epoch: 80 [3000/3859 (77%)]	Loss: 0.689194

MSE validation: 0.8527

Train Epoch: 81 [0/3859 (0%)]	Loss: 0.692237
Train Epoch: 81 [3000/3859 (77%)]	Loss: 0.834221

MSE validation: 0.8484

Train Epoch: 82 [0/3859 (0%)]	Loss: 0.826340
Train Epoch: 82 [3000/3859 (77%)]	Loss: 0.667123

MSE validation: 0.8446

Train Epoch: 83 [0/3859 (0%)]	Loss: 0.808936
Train Epoch: 83 [3000/3859 (77%)]	Loss: 0.901252

MSE validation: 0.8416

Train Epoch: 84 [0/3859 (0%)]	Loss: 1.129838
Train Epoch: 84 [3000/3859 (77%)]	Loss: 0.336817

MSE validation: 0.8390

Train Epoch: 85 [0/3859 (0%)]	Loss: 0.813691
Train Epoch: 85 [3000/3859 (77%)]	Loss: 0.484559

MSE validation: 0.8359

Train Epoch: 86 [0/3859 (0%)]	Loss: 0.425200
Train Epoch: 86 [3000/3859 (77%)]	Loss: 0.566594

MSE validation: 0.8322

Train Epoch: 87 [0/3859 (0%)]	Loss: 0.655073
Train Epoch: 87 [3000/3859 (77%)]	Loss: 0.682839

MSE validation: 0.8305

Train Epoch: 88 [0/3859 (0%)]	Loss: 0.605500
Train Epoch: 88 [3000/3859 (77%)]	Loss: 0.706250

MSE validation: 0.8278

Train Epoch: 89 [0/3859 (0%)]	Loss: 0.432848
Train Epoch: 89 [3000/3859 (77%)]	Loss: 0.514714

MSE validation: 0.8255

Train Epoch: 90 [0/3859 (0%)]	Loss: 0.778235
Train Epoch: 90 [3000/3859 (77%)]	Loss: 0.372763

MSE validation: 0.8239

Train Epoch: 91 [0/3859 (0%)]	Loss: 0.693504
Train Epoch: 91 [3000/3859 (77%)]	Loss: 0.770760

MSE validation: 0.8209

Train Epoch: 92 [0/3859 (0%)]	Loss: 0.971543
Train Epoch: 92 [3000/3859 (77%)]	Loss: 0.401170

MSE validation: 0.8197

Train Epoch: 93 [0/3859 (0%)]	Loss: 0.836940
Train Epoch: 93 [3000/3859 (77%)]	Loss: 0.616989

MSE validation: 0.8176

Train Epoch: 94 [0/3859 (0%)]	Loss: 1.151816
Train Epoch: 94 [3000/3859 (77%)]	Loss: 0.812268

MSE validation: 0.8160

Train Epoch: 95 [0/3859 (0%)]	Loss: 0.773628
Train Epoch: 95 [3000/3859 (77%)]	Loss: 1.020647

MSE validation: 0.8137

Train Epoch: 96 [0/3859 (0%)]	Loss: 0.739173
Train Epoch: 96 [3000/3859 (77%)]	Loss: 0.825505

MSE validation: 0.8123

Train Epoch: 97 [0/3859 (0%)]	Loss: 0.632852
Train Epoch: 97 [3000/3859 (77%)]	Loss: 0.613531

MSE validation: 0.8106

Train Epoch: 98 [0/3859 (0%)]	Loss: 0.364874
Train Epoch: 98 [3000/3859 (77%)]	Loss: 0.436990

MSE validation: 0.8086

Train Epoch: 99 [0/3859 (0%)]	Loss: 0.498563
Train Epoch: 99 [3000/3859 (77%)]	Loss: 0.641917

MSE validation: 0.8093

Train Epoch: 100 [0/3859 (0%)]	Loss: 1.160419
Train Epoch: 100 [3000/3859 (77%)]	Loss: 0.680568

MSE validation: 0.8074

Train Epoch: 101 [0/3859 (0%)]	Loss: 0.740810
Train Epoch: 101 [3000/3859 (77%)]	Loss: 0.854156

MSE validation: 0.8057

Train Epoch: 102 [0/3859 (0%)]	Loss: 0.708453
Train Epoch: 102 [3000/3859 (77%)]	Loss: 0.692858

MSE validation: 0.8040

Train Epoch: 103 [0/3859 (0%)]	Loss: 0.851771
Train Epoch: 103 [3000/3859 (77%)]	Loss: 0.818806

MSE validation: 0.8028

Train Epoch: 104 [0/3859 (0%)]	Loss: 0.659299
Train Epoch: 104 [3000/3859 (77%)]	Loss: 0.283417

MSE validation: 0.8023

Train Epoch: 105 [0/3859 (0%)]	Loss: 0.822141
Train Epoch: 105 [3000/3859 (77%)]	Loss: 0.900852

MSE validation: 0.8011

Train Epoch: 106 [0/3859 (0%)]	Loss: 0.570057
Train Epoch: 106 [3000/3859 (77%)]	Loss: 1.247744

MSE validation: 0.8009

Train Epoch: 107 [0/3859 (0%)]	Loss: 0.523276
Train Epoch: 107 [3000/3859 (77%)]	Loss: 0.861850

MSE validation: 0.7998

Train Epoch: 108 [0/3859 (0%)]	Loss: 0.597591
Train Epoch: 108 [3000/3859 (77%)]	Loss: 0.416984

MSE validation: 0.7984

Train Epoch: 109 [0/3859 (0%)]	Loss: 0.434038
Train Epoch: 109 [3000/3859 (77%)]	Loss: 0.572141

MSE validation: 0.7974

Train Epoch: 110 [0/3859 (0%)]	Loss: 0.516846
Train Epoch: 110 [3000/3859 (77%)]	Loss: 0.479634

MSE validation: 0.7969

Train Epoch: 111 [0/3859 (0%)]	Loss: 0.357616
Train Epoch: 111 [3000/3859 (77%)]	Loss: 0.640755

MSE validation: 0.7958

Train Epoch: 112 [0/3859 (0%)]	Loss: 0.640530
Train Epoch: 112 [3000/3859 (77%)]	Loss: 0.733959

MSE validation: 0.7957

Train Epoch: 113 [0/3859 (0%)]	Loss: 0.941620
Train Epoch: 113 [3000/3859 (77%)]	Loss: 0.714317

MSE validation: 0.7948

Train Epoch: 114 [0/3859 (0%)]	Loss: 0.694322
Train Epoch: 114 [3000/3859 (77%)]	Loss: 0.596692

MSE validation: 0.7948

Train Epoch: 115 [0/3859 (0%)]	Loss: 0.506504
Train Epoch: 115 [3000/3859 (77%)]	Loss: 0.699171

MSE validation: 0.7924

Train Epoch: 116 [0/3859 (0%)]	Loss: 0.628069
Train Epoch: 116 [3000/3859 (77%)]	Loss: 0.644691

MSE validation: 0.7922

Train Epoch: 117 [0/3859 (0%)]	Loss: 0.595123
Train Epoch: 117 [3000/3859 (77%)]	Loss: 0.612150

MSE validation: 0.7936

Train Epoch: 118 [0/3859 (0%)]	Loss: 0.586927
Train Epoch: 118 [3000/3859 (77%)]	Loss: 0.864691

MSE validation: 0.7907

Train Epoch: 119 [0/3859 (0%)]	Loss: 0.663839
Train Epoch: 119 [3000/3859 (77%)]	Loss: 0.860504

MSE validation: 0.7905

Train Epoch: 120 [0/3859 (0%)]	Loss: 0.475446
Train Epoch: 120 [3000/3859 (77%)]	Loss: 0.594122

MSE validation: 0.7898

Train Epoch: 121 [0/3859 (0%)]	Loss: 0.531715
Train Epoch: 121 [3000/3859 (77%)]	Loss: 0.517217

MSE validation: 0.7909

Train Epoch: 122 [0/3859 (0%)]	Loss: 0.372397
Train Epoch: 122 [3000/3859 (77%)]	Loss: 0.753812

MSE validation: 0.7900

Train Epoch: 123 [0/3859 (0%)]	Loss: 0.391624
Train Epoch: 123 [3000/3859 (77%)]	Loss: 0.997173

MSE validation: 0.7886

Train Epoch: 124 [0/3859 (0%)]	Loss: 0.461461
Train Epoch: 124 [3000/3859 (77%)]	Loss: 0.458879

MSE validation: 0.7898

Train Epoch: 125 [0/3859 (0%)]	Loss: 0.401302
Train Epoch: 125 [3000/3859 (77%)]	Loss: 0.816661

MSE validation: 0.7888

Train Epoch: 126 [0/3859 (0%)]	Loss: 0.501526
Train Epoch: 126 [3000/3859 (77%)]	Loss: 0.605357

MSE validation: 0.7881

Train Epoch: 127 [0/3859 (0%)]	Loss: 0.791805
Train Epoch: 127 [3000/3859 (77%)]	Loss: 0.379357

MSE validation: 0.7893

Train Epoch: 128 [0/3859 (0%)]	Loss: 0.666900
Train Epoch: 128 [3000/3859 (77%)]	Loss: 0.559550

MSE validation: 0.7868

Train Epoch: 129 [0/3859 (0%)]	Loss: 0.796738
Train Epoch: 129 [3000/3859 (77%)]	Loss: 0.648190

MSE validation: 0.7871

Train Epoch: 130 [0/3859 (0%)]	Loss: 1.000362
Train Epoch: 130 [3000/3859 (77%)]	Loss: 0.481748

MSE validation: 0.7865

Train Epoch: 131 [0/3859 (0%)]	Loss: 0.897954
Train Epoch: 131 [3000/3859 (77%)]	Loss: 0.556217

MSE validation: 0.7860

Train Epoch: 132 [0/3859 (0%)]	Loss: 0.757628
Train Epoch: 132 [3000/3859 (77%)]	Loss: 0.539894

MSE validation: 0.7862

Train Epoch: 133 [0/3859 (0%)]	Loss: 0.423837
Train Epoch: 133 [3000/3859 (77%)]	Loss: 0.688208

MSE validation: 0.7852

Train Epoch: 134 [0/3859 (0%)]	Loss: 0.679197
Train Epoch: 134 [3000/3859 (77%)]	Loss: 0.810797

MSE validation: 0.7850

Train Epoch: 135 [0/3859 (0%)]	Loss: 0.640856
Train Epoch: 135 [3000/3859 (77%)]	Loss: 0.735366

MSE validation: 0.7856

Train Epoch: 136 [0/3859 (0%)]	Loss: 0.394873
Train Epoch: 136 [3000/3859 (77%)]	Loss: 0.633972

MSE validation: 0.7868

Train Epoch: 137 [0/3859 (0%)]	Loss: 0.579043
Train Epoch: 137 [3000/3859 (77%)]	Loss: 0.582266

MSE validation: 0.7858

Train Epoch: 138 [0/3859 (0%)]	Loss: 0.712975
Train Epoch: 138 [3000/3859 (77%)]	Loss: 0.686939

MSE validation: 0.7845

Train Epoch: 139 [0/3859 (0%)]	Loss: 0.412686
Train Epoch: 139 [3000/3859 (77%)]	Loss: 0.725586

MSE validation: 0.7845

Train Epoch: 140 [0/3859 (0%)]	Loss: 0.637433
Train Epoch: 140 [3000/3859 (77%)]	Loss: 0.722663

MSE validation: 0.7839

Train Epoch: 141 [0/3859 (0%)]	Loss: 0.542507
Train Epoch: 141 [3000/3859 (77%)]	Loss: 0.672354

MSE validation: 0.7846

Train Epoch: 142 [0/3859 (0%)]	Loss: 0.438677
Train Epoch: 142 [3000/3859 (77%)]	Loss: 0.614347

MSE validation: 0.7834

Train Epoch: 143 [0/3859 (0%)]	Loss: 0.676312
Train Epoch: 143 [3000/3859 (77%)]	Loss: 0.868792

MSE validation: 0.7840

Train Epoch: 144 [0/3859 (0%)]	Loss: 0.402524
Train Epoch: 144 [3000/3859 (77%)]	Loss: 0.508541

MSE validation: 0.7859

Train Epoch: 145 [0/3859 (0%)]	Loss: 0.731991
Train Epoch: 145 [3000/3859 (77%)]	Loss: 0.411207

MSE validation: 0.7866

Train Epoch: 146 [0/3859 (0%)]	Loss: 0.378976
Train Epoch: 146 [3000/3859 (77%)]	Loss: 0.776918

MSE validation: 0.7820

Train Epoch: 147 [0/3859 (0%)]	Loss: 0.881870
Train Epoch: 147 [3000/3859 (77%)]	Loss: 0.712054

MSE validation: 0.7827

Train Epoch: 148 [0/3859 (0%)]	Loss: 0.578808
Train Epoch: 148 [3000/3859 (77%)]	Loss: 0.796217

MSE validation: 0.7828

Train Epoch: 149 [0/3859 (0%)]	Loss: 0.666108
Train Epoch: 149 [3000/3859 (77%)]	Loss: 0.513666

MSE validation: 0.7821

Train Epoch: 150 [0/3859 (0%)]	Loss: 0.543442
Train Epoch: 150 [3000/3859 (77%)]	Loss: 0.649746

MSE validation: 0.7833

Train Epoch: 151 [0/3859 (0%)]	Loss: 0.712575
Train Epoch: 151 [3000/3859 (77%)]	Loss: 0.395672

MSE validation: 0.7847

Train Epoch: 152 [0/3859 (0%)]	Loss: 0.750246
Train Epoch: 152 [3000/3859 (77%)]	Loss: 0.642491

MSE validation: 0.7831

Train Epoch: 153 [0/3859 (0%)]	Loss: 0.718959
Train Epoch: 153 [3000/3859 (77%)]	Loss: 0.968628

MSE validation: 0.7838

Train Epoch: 154 [0/3859 (0%)]	Loss: 0.567557
Train Epoch: 154 [3000/3859 (77%)]	Loss: 0.823994

MSE validation: 0.7816

Train Epoch: 155 [0/3859 (0%)]	Loss: 0.744882
Train Epoch: 155 [3000/3859 (77%)]	Loss: 0.547626

MSE validation: 0.7825

Train Epoch: 156 [0/3859 (0%)]	Loss: 1.149307
Train Epoch: 156 [3000/3859 (77%)]	Loss: 0.628469

MSE validation: 0.7831

Train Epoch: 157 [0/3859 (0%)]	Loss: 0.694507
Train Epoch: 157 [3000/3859 (77%)]	Loss: 0.676608

MSE validation: 0.7825

Train Epoch: 158 [0/3859 (0%)]	Loss: 0.707577
Train Epoch: 158 [3000/3859 (77%)]	Loss: 0.765637

MSE validation: 0.7834

Train Epoch: 159 [0/3859 (0%)]	Loss: 0.545907
Train Epoch: 159 [3000/3859 (77%)]	Loss: 0.538537

MSE validation: 0.7824

Train Epoch: 160 [0/3859 (0%)]	Loss: 0.575328
Train Epoch: 160 [3000/3859 (77%)]	Loss: 0.430648

MSE validation: 0.7817

Train Epoch: 161 [0/3859 (0%)]	Loss: 0.900222
Train Epoch: 161 [3000/3859 (77%)]	Loss: 0.572164

MSE validation: 0.7815

Train Epoch: 162 [0/3859 (0%)]	Loss: 0.686906
Train Epoch: 162 [3000/3859 (77%)]	Loss: 0.438355

MSE validation: 0.7824

Train Epoch: 163 [0/3859 (0%)]	Loss: 0.719146
Train Epoch: 163 [3000/3859 (77%)]	Loss: 0.452845

MSE validation: 0.7848

Train Epoch: 164 [0/3859 (0%)]	Loss: 0.545044
Train Epoch: 164 [3000/3859 (77%)]	Loss: 0.533672

MSE validation: 0.7808

Train Epoch: 165 [0/3859 (0%)]	Loss: 0.405713
Train Epoch: 165 [3000/3859 (77%)]	Loss: 0.480311

MSE validation: 0.7793

Train Epoch: 166 [0/3859 (0%)]	Loss: 0.617316
Train Epoch: 166 [3000/3859 (77%)]	Loss: 0.736882

MSE validation: 0.7833

Train Epoch: 167 [0/3859 (0%)]	Loss: 0.760726
Train Epoch: 167 [3000/3859 (77%)]	Loss: 0.539482
