# Treinamento com interface de alto nível

## Importação das bibliotecas

In [1]:
# http://pytorch.org/
from os.path import exists

import torch

In [2]:
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.utils.data import Dataset, random_split
from torch.optim.lr_scheduler import StepLR

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split

# Dataset

In [5]:
#!/bin/bash
!curl -L -o /content/life-expectancy-who.zip https://www.kaggle.com/api/v1/datasets/download/kumarajarshi/life-expectancy-who

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  118k  100  118k    0     0   247k      0 --:--:-- --:--:-- --:--:-- 6243k

In [6]:
!unzip -o /content/life-expectancy-who.zip -d /content/life-expectancy-who

Archive:  /content/life-expectancy-who.zip
  inflating: /content/life-expectancy-who/Life Expectancy Data.csv

In [9]:
life_expectancy_who_csv = "/content/life-expectancy-who/Life Expectancy Data.csv"

In [10]:
df = pd.read_csv(life_expectancy_who_csv)
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Life expectancy                  2928 non-null   float64
 4   Adult Mortality                  2928 non-null   float64
 5   infant deaths                    2938 non-null   int64
 6   Alcohol                          2744 non-null   float64
 7   percentage expenditure           2938 non-null   float64
 8   Hepatitis B                      2385 non-null   float64
 9   Measles                          2938 non-null   int64
 10   BMI                             2904 non-null   float64
 11  under-five deaths                2938 non-null   int64
 12  Polio                            2919 non-null   float64
 13  Total expenditure                2712 non-null   float64
 14  Diphtheria                       2919 non-null   float64
 15   HIV/AIDS                        2938 non-null   float64
 16  GDP                              2490 non-null   float64
 17  Population                       2286 non-null   float64
 18   thinness  1-19 years            2904 non-null   float64
 19   thinness 5-9 years              2904 non-null   float64
 20  Income composition of resources  2771 non-null   float64
 21  Schooling                        2775 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [18]:
df.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

In [15]:
df.nunique()

Country                             193
Year                                 16
Status                                2
Life expectancy                     362
Adult Mortality                     425
infant deaths                       209
Alcohol                            1076
percentage expenditure             2328
Hepatitis B                          87
Measles                             958
 BMI                                608
under-five deaths                   252
Polio                                73
Total expenditure                   818
Diphtheria                           81
 HIV/AIDS                           200
GDP                                2490
Population                         2278
 thinness  1-19 years               200
 thinness 5-9 years                 207
Income composition of resources     625
Schooling                           173
dtype: int64

In [16]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [17]:
#Removendo dados Nulos
for col in df.columns:
  if df[col].dtype != object:
    df.loc[df[col].isnull(), col] = df[col].mean()

<ipython-input-17-d0f31bc3c11b>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2007.5187202178352' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[col].isnull(), col] = df[col].mean()
<ipython-input-17-d0f31bc3c11b>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '30.303948264125257' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[col].isnull(), col] = df[col].mean()
<ipython-input-17-d0f31bc3c11b>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2419.5922396187884' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[col].isnull(), col] = df[col].mean()
<ipython-input-17-d0f31bc3c11b>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '42.0357385976855' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df[col].isnull(), col] = df[col].mean()

In [19]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015.0,Developing,65.0,263.0,62.0,0.01,71.279624,65.0,1154.0,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014.0,Developing,59.9,271.0,64.0,0.01,73.523582,62.0,492.0,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013.0,Developing,59.9,268.0,66.0,0.01,73.219243,64.0,430.0,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012.0,Developing,59.5,272.0,69.0,0.01,78.184215,67.0,2787.0,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011.0,Developing,59.2,275.0,71.0,0.01,7.097109,68.0,3013.0,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [20]:
categorical_columns = ["Country", "Status"]
for col in categorical_columns:
  print(f"Categoria na {col}: {df[col].unique()}")

Categoria na Country: ['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Antigua and Barbuda'
 'Argentina' 'Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin'
 'Bhutan' 'Bolivia (Plurinational State of)' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei Darussalam' 'Bulgaria' 'Burkina Faso'
 'Burundi' "Côte d'Ivoire" 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Cook Islands' 'Costa Rica' 'Croatia' 'Cuba' 'Cyprus' 'Czechia'
 "Democratic People's Republic of Korea"
 'Democratic Republic of the Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Ethiopia' 'Fiji' 'Finland' 'France' 'Gabon' 'Gambia'
 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada' 'Guatemala' 'Guinea'
 'Guinea-Bissau' 'Guyana' 'Haiti' 'Honduras' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran (Islamic Republic of)' 'Iraq' 'Ireland' 'Israel'
 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kuwait' 'Kyrgyzstan' "Lao People's Democratic Republic" 'Latvia'
 'Lebanon' 'Lesotho' 'Liberia' 'Libya' 'Lithuania' 'Luxembourg'
 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Mauritania' 'Mauritius' 'Mexico'
 'Micronesia (Federated States of)' 'Monaco' 'Mongolia' 'Montenegro'
 'Morocco' 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue' 'Norway' 'Oman'
 'Pakistan' 'Palau' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Republic of Korea'
 'Republic of Moldova' 'Romania' 'Russian Federation' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'Samoa' 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia'
 'Solomon Islands' 'Somalia' 'South Africa' 'South Sudan' 'Spain'
 'Sri Lanka' 'Sudan' 'Suriname' 'Swaziland' 'Sweden' 'Switzerland'
 'Syrian Arab Republic' 'Tajikistan' 'Thailand'
 'The former Yugoslav republic of Macedonia' 'Timor-Leste' 'Togo' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan' 'Tuvalu' 'Uganda'
 'Ukraine' 'United Arab Emirates'
 'United Kingdom of Great Britain and Northern Ireland'
 'United Republic of Tanzania' 'United States of America' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Venezuela (Bolivarian Republic of)' 'Viet Nam'
 'Yemen' 'Zambia' 'Zimbabwe']
Categoria na Status: ['Developing' 'Developed']

In [21]:
Country_encoded = LabelEncoder()
df["Country"] = Country_encoded.fit_transform(df["Country"])

Status_encoded = LabelEncoder()
df["Status"] = Status_encoded.fit_transform(df["Status"])

In [22]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,0,2015.0,1,65.0,263.0,62.0,0.01,71.279624,65.0,1154.0,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,0,2014.0,1,59.9,271.0,64.0,0.01,73.523582,62.0,492.0,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,0,2013.0,1,59.9,268.0,66.0,0.01,73.219243,64.0,430.0,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,0,2012.0,1,59.5,272.0,69.0,0.01,78.184215,67.0,2787.0,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,0,2011.0,1,59.2,275.0,71.0,0.01,7.097109,68.0,3013.0,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [23]:
standart_scaler = StandardScaler()
new_df = pd.DataFrame(standart_scaler.fit_transform(df), columns=df.columns)

In [24]:
new_df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,-1.691042,1.621762,0.459399,-0.444448,0.791586,0.268824,-1.172958,-0.335570,-0.705861,-0.110384,...,-3.278638,0.925806,-0.732952,-0.323445,-0.525248,0.389975,2.813130,2.773279,-0.725401,-0.579931
1,-1.691042,1.404986,0.459399,-0.980950,0.856072,0.285786,-1.172958,-0.334441,-0.838704,-0.168124,...,-1.051482,0.934140,-0.859877,-0.323445,-0.523083,-0.230936,2.881408,2.817902,-0.740050,-0.610570
2,-1.691042,1.188210,0.459399,-0.980950,0.831890,0.302749,-1.172958,-0.334594,-0.750142,-0.173531,...,-0.880163,0.913306,-0.775260,-0.323445,-0.521632,0.352715,2.926927,2.862526,-0.769349,-0.641209
3,-1.691042,0.971434,0.459399,-1.023029,0.864132,0.328193,-1.172958,-0.332096,-0.617299,0.032045,...,-0.666013,1.075815,-0.648335,-0.323445,-0.518723,-0.168315,2.972446,2.929461,-0.803531,-0.671847
4,-1.691042,0.754658,0.459399,-1.054587,0.888314,0.345155,-1.172958,-0.367862,-0.573018,0.051757,...,-0.623183,0.804966,-0.606027,-0.323445,-0.564893,-0.181666,3.040724,2.974085,-0.847480,-0.763764

In [25]:
y = new_df["Life expectancy "]
x = new_df[new_df.columns.difference(["Life expectancy "])]

In [26]:
y = y.values.reshape(-1, 1)
x = x.to_numpy()

In [27]:
x.shape

(2938, 21)

In [28]:
y.shape

(2938, 1)

In [29]:
class LifeExpectancyDataset(Dataset):
  def __init__(self, x, y):
    super(LifeExpectancyDataset, self).__init__()
    if(len(x) != len(y)):
      raise ValueError("Size de X e Y não dão match!")
    self.x = torch.FloatTensor(x)
    self.y = torch.FloatTensor(y)
    self.x = torch.nan_to_num(self.x)
    self.y = torch.nan_to_num(self.y)

  def __getitem__(self, index):
     return self.x[index], self.y[index]

  def __len__(self):
    return len(self.x)

In [30]:
dataset = LifeExpectancyDataset(x, y)

In [32]:
train_data, val_data = random_split(dataset, [0.8, 0.2])

In [33]:
print(f"len treinamento: {len(train_data)}")

len treinamento: 2351

In [34]:
print(f"len val: {len(val_data)}")

len val: 587

In [35]:
x.shape

(2938, 21)

## Criação da rede

In [36]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Sequential(
            nn.Linear(21, 32),
            nn.ReLU(),
            nn.Linear(32, 64),
            nn.ReLU(),
            nn.Linear(64, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, x):
        output = self.fc(x)
        return output

model = Net()

In [37]:
model

Net(
  (fc): Sequential(
    (0): Linear(in_features=21, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=64, bias=True)
    (3): ReLU()
    (4): Linear(in_features=64, out_features=128, bias=True)
    (5): ReLU()
    (6): Linear(in_features=128, out_features=64, bias=True)
    (7): ReLU()
    (8): Linear(in_features=64, out_features=32, bias=True)
    (9): ReLU()
    (10): Linear(in_features=32, out_features=1, bias=True)
  )
)

## Treinamento

### Criando o objeto de treinamento

In [38]:
def train(log_interval, dry_run, model, device, train_loader, optimizer, epoch, criterion):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))
            if dry_run:
                break

In [39]:
def test(model, device, test_loader, criterion):
    model.eval()
    total_loss = 0
    total_samples = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            output = model(data)
            loss = criterion(output, target)
            total_loss += loss.item() * target.size(0)
            total_samples += target.size(0)
        mse = total_loss / total_samples
        print(f"\nMSE validation: {mse:.4f}\n")
    return mse

## Avaliação

In [40]:
use_cuda = torch.cuda.is_available()

torch.manual_seed(1111)

device = torch.device("cuda" if use_cuda else "cpu")

train_kwargs = {'batch_size': 300}
test_kwargs = {'batch_size': 100}
if use_cuda:
    cuda_kwargs = {'num_workers': 1,
                    'pin_memory': True,
                    'shuffle': True}
    train_kwargs.update(cuda_kwargs)
    test_kwargs.update(cuda_kwargs)

train_loader = torch.utils.data.DataLoader(train_data,**train_kwargs)
test_loader = torch.utils.data.DataLoader(val_data, **test_kwargs)
model = Net().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)
criterion = nn.MSELoss()
best_loss = test(model, device, test_loader, criterion)
epochs = 300
# scheduler = StepLR(optimizer, step_size=1, gamma=0.7)

for epoch in range(1, epochs + 1):
    train(10, False, model, device, train_loader, optimizer, epoch, criterion)
    loss = test(model, device, test_loader, criterion)
    if (loss < best_loss):
      best_loss = loss
      torch.save(model.state_dict(), "life_expectancy_nn.pt")

MSE validation: 1.0535

Train Epoch: 1 [0/2351 (0%)]	Loss: 0.982806

MSE validation: 1.0518

Train Epoch: 2 [0/2351 (0%)]	Loss: 0.899256

MSE validation: 1.0505

Train Epoch: 3 [0/2351 (0%)]	Loss: 1.030280

MSE validation: 1.0493

Train Epoch: 4 [0/2351 (0%)]	Loss: 1.039999

MSE validation: 1.0481

Train Epoch: 5 [0/2351 (0%)]	Loss: 1.005894

MSE validation: 1.0469

Train Epoch: 6 [0/2351 (0%)]	Loss: 1.029395

MSE validation: 1.0457

Train Epoch: 7 [0/2351 (0%)]	Loss: 1.161648

MSE validation: 1.0444

Train Epoch: 8 [0/2351 (0%)]	Loss: 0.898010

MSE validation: 1.0431

Train Epoch: 9 [0/2351 (0%)]	Loss: 0.940454

MSE validation: 1.0418

Train Epoch: 10 [0/2351 (0%)]	Loss: 1.004956

MSE validation: 1.0404

Train Epoch: 11 [0/2351 (0%)]	Loss: 0.904588

MSE validation: 1.0390

Train Epoch: 12 [0/2351 (0%)]	Loss: 1.064717

MSE validation: 1.0374

Train Epoch: 13 [0/2351 (0%)]	Loss: 0.842894

MSE validation: 1.0358

Train Epoch: 14 [0/2351 (0%)]	Loss: 0.986533

MSE validation: 1.0340

Train Epoch: 15 [0/2351 (0%)]	Loss: 0.905569

MSE validation: 1.0321

Train Epoch: 16 [0/2351 (0%)]	Loss: 1.084554

MSE validation: 1.0300

Train Epoch: 17 [0/2351 (0%)]	Loss: 0.918542

MSE validation: 1.0278

Train Epoch: 18 [0/2351 (0%)]	Loss: 0.943576

MSE validation: 1.0253

Train Epoch: 19 [0/2351 (0%)]	Loss: 0.925110

MSE validation: 1.0225

Train Epoch: 20 [0/2351 (0%)]	Loss: 0.954189

MSE validation: 1.0195

Train Epoch: 21 [0/2351 (0%)]	Loss: 0.957237

MSE validation: 1.0162

Train Epoch: 22 [0/2351 (0%)]	Loss: 0.998721

MSE validation: 1.0125

Train Epoch: 23 [0/2351 (0%)]	Loss: 0.856819

MSE validation: 1.0084

Train Epoch: 24 [0/2351 (0%)]	Loss: 0.930004

MSE validation: 1.0039

Train Epoch: 25 [0/2351 (0%)]	Loss: 0.849692

MSE validation: 0.9988

Train Epoch: 26 [0/2351 (0%)]	Loss: 1.006533

MSE validation: 0.9932

Train Epoch: 27 [0/2351 (0%)]	Loss: 0.966193

MSE validation: 0.9868

Train Epoch: 28 [0/2351 (0%)]	Loss: 0.964459

MSE validation: 0.9797

Train Epoch: 29 [0/2351 (0%)]	Loss: 0.977032

MSE validation: 0.9716

Train Epoch: 30 [0/2351 (0%)]	Loss: 0.974808

MSE validation: 0.9623

Train Epoch: 31 [0/2351 (0%)]	Loss: 0.829384

MSE validation: 0.9518

Train Epoch: 32 [0/2351 (0%)]	Loss: 0.838191

MSE validation: 0.9397

Train Epoch: 33 [0/2351 (0%)]	Loss: 0.943329

MSE validation: 0.9259

Train Epoch: 34 [0/2351 (0%)]	Loss: 0.783192

MSE validation: 0.9101

Train Epoch: 35 [0/2351 (0%)]	Loss: 0.841391

MSE validation: 0.8919

Train Epoch: 36 [0/2351 (0%)]	Loss: 0.966924

MSE validation: 0.8710

Train Epoch: 37 [0/2351 (0%)]	Loss: 0.822478

MSE validation: 0.8470

Train Epoch: 38 [0/2351 (0%)]	Loss: 0.855953

MSE validation: 0.8196

Train Epoch: 39 [0/2351 (0%)]	Loss: 0.720586

MSE validation: 0.7883

Train Epoch: 40 [0/2351 (0%)]	Loss: 0.806308

MSE validation: 0.7528

Train Epoch: 41 [0/2351 (0%)]	Loss: 0.765126

MSE validation: 0.7129

Train Epoch: 42 [0/2351 (0%)]	Loss: 0.684735

MSE validation: 0.6686

Train Epoch: 43 [0/2351 (0%)]	Loss: 0.690207

MSE validation: 0.6202

Train Epoch: 44 [0/2351 (0%)]	Loss: 0.642449

MSE validation: 0.5685

Train Epoch: 45 [0/2351 (0%)]	Loss: 0.486602

MSE validation: 0.5154

Train Epoch: 46 [0/2351 (0%)]	Loss: 0.467679

MSE validation: 0.4632

Train Epoch: 47 [0/2351 (0%)]	Loss: 0.409830

MSE validation: 0.4141

Train Epoch: 48 [0/2351 (0%)]	Loss: 0.380240

MSE validation: 0.3705

Train Epoch: 49 [0/2351 (0%)]	Loss: 0.344290

MSE validation: 0.3337

Train Epoch: 50 [0/2351 (0%)]	Loss: 0.330447

MSE validation: 0.3045

Train Epoch: 51 [0/2351 (0%)]	Loss: 0.348638

MSE validation: 0.2818

Train Epoch: 52 [0/2351 (0%)]	Loss: 0.264828

MSE validation: 0.2647

Train Epoch: 53 [0/2351 (0%)]	Loss: 0.301233

MSE validation: 0.2515

Train Epoch: 54 [0/2351 (0%)]	Loss: 0.282168

MSE validation: 0.2411

Train Epoch: 55 [0/2351 (0%)]	Loss: 0.250849

MSE validation: 0.2326

Train Epoch: 56 [0/2351 (0%)]	Loss: 0.260447

MSE validation: 0.2257

Train Epoch: 57 [0/2351 (0%)]	Loss: 0.254323

MSE validation: 0.2198

Train Epoch: 58 [0/2351 (0%)]	Loss: 0.239891

MSE validation: 0.2143

Train Epoch: 59 [0/2351 (0%)]	Loss: 0.267780

MSE validation: 0.2097

Train Epoch: 60 [0/2351 (0%)]	Loss: 0.227700

MSE validation: 0.2050

Train Epoch: 61 [0/2351 (0%)]	Loss: 0.225475

MSE validation: 0.2010

Train Epoch: 62 [0/2351 (0%)]	Loss: 0.196200

MSE validation: 0.1975

Train Epoch: 63 [0/2351 (0%)]	Loss: 0.236695

MSE validation: 0.1945

Train Epoch: 64 [0/2351 (0%)]	Loss: 0.227062

MSE validation: 0.1918

Train Epoch: 65 [0/2351 (0%)]	Loss: 0.199788

MSE validation: 0.1891

Train Epoch: 66 [0/2351 (0%)]	Loss: 0.224851

MSE validation: 0.1869

Train Epoch: 67 [0/2351 (0%)]	Loss: 0.248363

MSE validation: 0.1847

Train Epoch: 68 [0/2351 (0%)]	Loss: 0.177252

MSE validation: 0.1826

Train Epoch: 69 [0/2351 (0%)]	Loss: 0.182566

MSE validation: 0.1808

Train Epoch: 70 [0/2351 (0%)]	Loss: 0.219835

MSE validation: 0.1789

Train Epoch: 71 [0/2351 (0%)]	Loss: 0.186459

MSE validation: 0.1773

Train Epoch: 72 [0/2351 (0%)]	Loss: 0.192997

MSE validation: 0.1758

Train Epoch: 73 [0/2351 (0%)]	Loss: 0.198678

MSE validation: 0.1745

Train Epoch: 74 [0/2351 (0%)]	Loss: 0.205606

MSE validation: 0.1733

Train Epoch: 75 [0/2351 (0%)]	Loss: 0.184184

MSE validation: 0.1719

Train Epoch: 76 [0/2351 (0%)]	Loss: 0.146382

MSE validation: 0.1704

Train Epoch: 77 [0/2351 (0%)]	Loss: 0.187887

MSE validation: 0.1695

Train Epoch: 78 [0/2351 (0%)]	Loss: 0.170637

MSE validation: 0.1682

Train Epoch: 79 [0/2351 (0%)]	Loss: 0.209985

MSE validation: 0.1672

Train Epoch: 80 [0/2351 (0%)]	Loss: 0.185167

MSE validation: 0.1661

Train Epoch: 81 [0/2351 (0%)]	Loss: 0.163934

MSE validation: 0.1651

Train Epoch: 82 [0/2351 (0%)]	Loss: 0.188073

MSE validation: 0.1643

Train Epoch: 83 [0/2351 (0%)]	Loss: 0.174787

MSE validation: 0.1633

Train Epoch: 84 [0/2351 (0%)]	Loss: 0.162973

MSE validation: 0.1627

Train Epoch: 85 [0/2351 (0%)]	Loss: 0.162393

MSE validation: 0.1615

Train Epoch: 86 [0/2351 (0%)]	Loss: 0.167014

MSE validation: 0.1610

Train Epoch: 87 [0/2351 (0%)]	Loss: 0.147168

MSE validation: 0.1601

Train Epoch: 88 [0/2351 (0%)]	Loss: 0.214423

MSE validation: 0.1593

Train Epoch: 89 [0/2351 (0%)]	Loss: 0.143645

MSE validation: 0.1586

Train Epoch: 90 [0/2351 (0%)]	Loss: 0.133428

MSE validation: 0.1580

Train Epoch: 91 [0/2351 (0%)]	Loss: 0.159696

MSE validation: 0.1570

Train Epoch: 92 [0/2351 (0%)]	Loss: 0.163881

MSE validation: 0.1565

Train Epoch: 93 [0/2351 (0%)]	Loss: 0.163989

MSE validation: 0.1557

Train Epoch: 94 [0/2351 (0%)]	Loss: 0.171493

MSE validation: 0.1552

Train Epoch: 95 [0/2351 (0%)]	Loss: 0.166898

MSE validation: 0.1546

Train Epoch: 96 [0/2351 (0%)]	Loss: 0.144758

MSE validation: 0.1540

Train Epoch: 97 [0/2351 (0%)]	Loss: 0.186285

MSE validation: 0.1533

Train Epoch: 98 [0/2351 (0%)]	Loss: 0.159265

MSE validation: 0.1527

Train Epoch: 99 [0/2351 (0%)]	Loss: 0.151669

MSE validation: 0.1522

Train Epoch: 100 [0/2351 (0%)]	Loss: 0.165405

MSE validation: 0.1518

Train Epoch: 101 [0/2351 (0%)]	Loss: 0.158749

MSE validation: 0.1514

Train Epoch: 102 [0/2351 (0%)]	Loss: 0.129888

MSE validation: 0.1506

Train Epoch: 103 [0/2351 (0%)]	Loss: 0.137158

MSE validation: 0.1501

Train Epoch: 104 [0/2351 (0%)]	Loss: 0.151022

MSE validation: 0.1495

Train Epoch: 105 [0/2351 (0%)]	Loss: 0.154072

MSE validation: 0.1492

Train Epoch: 106 [0/2351 (0%)]	Loss: 0.164178

MSE validation: 0.1487

Train Epoch: 107 [0/2351 (0%)]	Loss: 0.163956

MSE validation: 0.1483

Train Epoch: 108 [0/2351 (0%)]	Loss: 0.148450

MSE validation: 0.1479

Train Epoch: 109 [0/2351 (0%)]	Loss: 0.168078

MSE validation: 0.1476

Train Epoch: 110 [0/2351 (0%)]	Loss: 0.165209

MSE validation: 0.1468

Train Epoch: 111 [0/2351 (0%)]	Loss: 0.151584

MSE validation: 0.1466

Train Epoch: 112 [0/2351 (0%)]	Loss: 0.182936

MSE validation: 0.1460

Train Epoch: 113 [0/2351 (0%)]	Loss: 0.147174

MSE validation: 0.1456

Train Epoch: 114 [0/2351 (0%)]	Loss: 0.130747

MSE validation: 0.1451

Train Epoch: 115 [0/2351 (0%)]	Loss: 0.126056

MSE validation: 0.1448

Train Epoch: 116 [0/2351 (0%)]	Loss: 0.161189

MSE validation: 0.1444

Train Epoch: 117 [0/2351 (0%)]	Loss: 0.179747

MSE validation: 0.1440

Train Epoch: 118 [0/2351 (0%)]	Loss: 0.144141

MSE validation: 0.1435

Train Epoch: 119 [0/2351 (0%)]	Loss: 0.134883

MSE validation: 0.1433

Train Epoch: 120 [0/2351 (0%)]	Loss: 0.172794

MSE validation: 0.1430

Train Epoch: 121 [0/2351 (0%)]	Loss: 0.097850

MSE validation: 0.1424

Train Epoch: 122 [0/2351 (0%)]	Loss: 0.157653

MSE validation: 0.1421

Train Epoch: 123 [0/2351 (0%)]	Loss: 0.155734

MSE validation: 0.1417

Train Epoch: 124 [0/2351 (0%)]	Loss: 0.146453

MSE validation: 0.1415

Train Epoch: 125 [0/2351 (0%)]	Loss: 0.145368

MSE validation: 0.1411

Train Epoch: 126 [0/2351 (0%)]	Loss: 0.159133

MSE validation: 0.1408

Train Epoch: 127 [0/2351 (0%)]	Loss: 0.156033

MSE validation: 0.1403

Train Epoch: 128 [0/2351 (0%)]	Loss: 0.168624

MSE validation: 0.1400

Train Epoch: 129 [0/2351 (0%)]	Loss: 0.158332

MSE validation: 0.1397

Train Epoch: 130 [0/2351 (0%)]	Loss: 0.155035

MSE validation: 0.1394

Train Epoch: 131 [0/2351 (0%)]	Loss: 0.165825

MSE validation: 0.1389

Train Epoch: 132 [0/2351 (0%)]	Loss: 0.096936

MSE validation: 0.1387

Train Epoch: 133 [0/2351 (0%)]	Loss: 0.133906

MSE validation: 0.1383

Train Epoch: 134 [0/2351 (0%)]	Loss: 0.150193

MSE validation: 0.1384

Train Epoch: 135 [0/2351 (0%)]	Loss: 0.147523

MSE validation: 0.1381

Train Epoch: 136 [0/2351 (0%)]	Loss: 0.135612

MSE validation: 0.1375

Train Epoch: 137 [0/2351 (0%)]	Loss: 0.153136

MSE validation: 0.1371

Train Epoch: 138 [0/2351 (0%)]	Loss: 0.128890

MSE validation: 0.1369

Train Epoch: 139 [0/2351 (0%)]	Loss: 0.139256

MSE validation: 0.1366

Train Epoch: 140 [0/2351 (0%)]	Loss: 0.166255

MSE validation: 0.1362

Train Epoch: 141 [0/2351 (0%)]	Loss: 0.160832

MSE validation: 0.1359

Train Epoch: 142 [0/2351 (0%)]	Loss: 0.163838

MSE validation: 0.1355

Train Epoch: 143 [0/2351 (0%)]	Loss: 0.144568

MSE validation: 0.1356

Train Epoch: 144 [0/2351 (0%)]	Loss: 0.143803

MSE validation: 0.1349

Train Epoch: 145 [0/2351 (0%)]	Loss: 0.150670

MSE validation: 0.1347

Train Epoch: 146 [0/2351 (0%)]	Loss: 0.128571

MSE validation: 0.1344

Train Epoch: 147 [0/2351 (0%)]	Loss: 0.137048

MSE validation: 0.1342

Train Epoch: 148 [0/2351 (0%)]	Loss: 0.131923

MSE validation: 0.1338

Train Epoch: 149 [0/2351 (0%)]	Loss: 0.129401

MSE validation: 0.1335

Train Epoch: 150 [0/2351 (0%)]	Loss: 0.129333

MSE validation: 0.1333

Train Epoch: 151 [0/2351 (0%)]	Loss: 0.128938

MSE validation: 0.1330

Train Epoch: 152 [0/2351 (0%)]	Loss: 0.125696

MSE validation: 0.1327

Train Epoch: 153 [0/2351 (0%)]	Loss: 0.131712

MSE validation: 0.1325

Train Epoch: 154 [0/2351 (0%)]	Loss: 0.160926

MSE validation: 0.1322

Train Epoch: 155 [0/2351 (0%)]	Loss: 0.132061

MSE validation: 0.1320

Train Epoch: 156 [0/2351 (0%)]	Loss: 0.126732

MSE validation: 0.1316

Train Epoch: 157 [0/2351 (0%)]	Loss: 0.140486

MSE validation: 0.1314

Train Epoch: 158 [0/2351 (0%)]	Loss: 0.121768

MSE validation: 0.1312

Train Epoch: 159 [0/2351 (0%)]	Loss: 0.104769

MSE validation: 0.1309

Train Epoch: 160 [0/2351 (0%)]	Loss: 0.115677

MSE validation: 0.1307

Train Epoch: 161 [0/2351 (0%)]	Loss: 0.111507

MSE validation: 0.1304

Train Epoch: 162 [0/2351 (0%)]	Loss: 0.137683

MSE validation: 0.1301

Train Epoch: 163 [0/2351 (0%)]	Loss: 0.135451

MSE validation: 0.1299

Train Epoch: 164 [0/2351 (0%)]	Loss: 0.113916

MSE validation: 0.1296

Train Epoch: 165 [0/2351 (0%)]	Loss: 0.128343

MSE validation: 0.1294

Train Epoch: 166 [0/2351 (0%)]	Loss: 0.118932

MSE validation: 0.1292

Train Epoch: 167 [0/2351 (0%)]	Loss: 0.124658

MSE validation: 0.1289

Train Epoch: 168 [0/2351 (0%)]	Loss: 0.132248

MSE validation: 0.1288

Train Epoch: 169 [0/2351 (0%)]	Loss: 0.133038

MSE validation: 0.1284

Train Epoch: 170 [0/2351 (0%)]	Loss: 0.120715

MSE validation: 0.1282

Train Epoch: 171 [0/2351 (0%)]	Loss: 0.131021

MSE validation: 0.1280

Train Epoch: 172 [0/2351 (0%)]	Loss: 0.139832

MSE validation: 0.1278

Train Epoch: 173 [0/2351 (0%)]	Loss: 0.151387

MSE validation: 0.1275

Train Epoch: 174 [0/2351 (0%)]	Loss: 0.145412

MSE validation: 0.1273

Train Epoch: 175 [0/2351 (0%)]	Loss: 0.103170

MSE validation: 0.1271

Train Epoch: 176 [0/2351 (0%)]	Loss: 0.141241

MSE validation: 0.1269

Train Epoch: 177 [0/2351 (0%)]	Loss: 0.106143

MSE validation: 0.1267

Train Epoch: 178 [0/2351 (0%)]	Loss: 0.127054

MSE validation: 0.1264

Train Epoch: 179 [0/2351 (0%)]	Loss: 0.143180

MSE validation: 0.1262

Train Epoch: 180 [0/2351 (0%)]	Loss: 0.116246

MSE validation: 0.1260

Train Epoch: 181 [0/2351 (0%)]	Loss: 0.159348

MSE validation: 0.1258

Train Epoch: 182 [0/2351 (0%)]	Loss: 0.098689

MSE validation: 0.1255

Train Epoch: 183 [0/2351 (0%)]	Loss: 0.130266

MSE validation: 0.1253

Train Epoch: 184 [0/2351 (0%)]	Loss: 0.120271

MSE validation: 0.1252

Train Epoch: 185 [0/2351 (0%)]	Loss: 0.134563

MSE validation: 0.1249

Train Epoch: 186 [0/2351 (0%)]	Loss: 0.140673

MSE validation: 0.1247

Train Epoch: 187 [0/2351 (0%)]	Loss: 0.136837

MSE validation: 0.1245

Train Epoch: 188 [0/2351 (0%)]	Loss: 0.114101

MSE validation: 0.1243

Train Epoch: 189 [0/2351 (0%)]	Loss: 0.123053

MSE validation: 0.1241

Train Epoch: 190 [0/2351 (0%)]	Loss: 0.113384

MSE validation: 0.1239

Train Epoch: 191 [0/2351 (0%)]	Loss: 0.125113

MSE validation: 0.1237

Train Epoch: 192 [0/2351 (0%)]	Loss: 0.144932

MSE validation: 0.1235

Train Epoch: 193 [0/2351 (0%)]	Loss: 0.130230

MSE validation: 0.1233

Train Epoch: 194 [0/2351 (0%)]	Loss: 0.142917

MSE validation: 0.1231

Train Epoch: 195 [0/2351 (0%)]	Loss: 0.117677

MSE validation: 0.1230

Train Epoch: 196 [0/2351 (0%)]	Loss: 0.132429

MSE validation: 0.1227

Train Epoch: 197 [0/2351 (0%)]	Loss: 0.116143

MSE validation: 0.1225

Train Epoch: 198 [0/2351 (0%)]	Loss: 0.132533

MSE validation: 0.1223

Train Epoch: 199 [0/2351 (0%)]	Loss: 0.113321

MSE validation: 0.1222

Train Epoch: 200 [0/2351 (0%)]	Loss: 0.148461

MSE validation: 0.1218

Train Epoch: 201 [0/2351 (0%)]	Loss: 0.111592

MSE validation: 0.1217

Train Epoch: 202 [0/2351 (0%)]	Loss: 0.123996

MSE validation: 0.1214

Train Epoch: 203 [0/2351 (0%)]	Loss: 0.126918

MSE validation: 0.1215

Train Epoch: 204 [0/2351 (0%)]	Loss: 0.124926

MSE validation: 0.1211

Train Epoch: 205 [0/2351 (0%)]	Loss: 0.110969

MSE validation: 0.1209

Train Epoch: 206 [0/2351 (0%)]	Loss: 0.108740

MSE validation: 0.1207

Train Epoch: 207 [0/2351 (0%)]	Loss: 0.113042

MSE validation: 0.1205

Train Epoch: 208 [0/2351 (0%)]	Loss: 0.140039

MSE validation: 0.1203

Train Epoch: 209 [0/2351 (0%)]	Loss: 0.124584

MSE validation: 0.1202

Train Epoch: 210 [0/2351 (0%)]	Loss: 0.121557

MSE validation: 0.1199

Train Epoch: 211 [0/2351 (0%)]	Loss: 0.110286

MSE validation: 0.1197

Train Epoch: 212 [0/2351 (0%)]	Loss: 0.127825

MSE validation: 0.1196

Train Epoch: 213 [0/2351 (0%)]	Loss: 0.140586

MSE validation: 0.1194

Train Epoch: 214 [0/2351 (0%)]	Loss: 0.116740

MSE validation: 0.1192

Train Epoch: 215 [0/2351 (0%)]	Loss: 0.128365

MSE validation: 0.1191

Train Epoch: 216 [0/2351 (0%)]	Loss: 0.124995

MSE validation: 0.1189

Train Epoch: 217 [0/2351 (0%)]	Loss: 0.116700

MSE validation: 0.1187

Train Epoch: 218 [0/2351 (0%)]	Loss: 0.120093

MSE validation: 0.1185

Train Epoch: 219 [0/2351 (0%)]	Loss: 0.114930

MSE validation: 0.1183

Train Epoch: 220 [0/2351 (0%)]	Loss: 0.143071

MSE validation: 0.1182

Train Epoch: 221 [0/2351 (0%)]	Loss: 0.132280

MSE validation: 0.1180

Train Epoch: 222 [0/2351 (0%)]	Loss: 0.121088

MSE validation: 0.1179

Train Epoch: 223 [0/2351 (0%)]	Loss: 0.107621

MSE validation: 0.1177

Train Epoch: 224 [0/2351 (0%)]	Loss: 0.123087

MSE validation: 0.1175

Train Epoch: 225 [0/2351 (0%)]	Loss: 0.125705

MSE validation: 0.1173

Train Epoch: 226 [0/2351 (0%)]	Loss: 0.128788

MSE validation: 0.1172

Train Epoch: 227 [0/2351 (0%)]	Loss: 0.125808

MSE validation: 0.1170

Train Epoch: 228 [0/2351 (0%)]	Loss: 0.142718

MSE validation: 0.1168

Train Epoch: 229 [0/2351 (0%)]	Loss: 0.108622

MSE validation: 0.1167

Train Epoch: 230 [0/2351 (0%)]	Loss: 0.122269

MSE validation: 0.1165

Train Epoch: 231 [0/2351 (0%)]	Loss: 0.119939

MSE validation: 0.1163

Train Epoch: 232 [0/2351 (0%)]	Loss: 0.102613

MSE validation: 0.1162

Train Epoch: 233 [0/2351 (0%)]	Loss: 0.113044

MSE validation: 0.1160

Train Epoch: 234 [0/2351 (0%)]	Loss: 0.137482

MSE validation: 0.1159

Train Epoch: 235 [0/2351 (0%)]	Loss: 0.104125

MSE validation: 0.1157

Train Epoch: 236 [0/2351 (0%)]	Loss: 0.105101

MSE validation: 0.1156

Train Epoch: 237 [0/2351 (0%)]	Loss: 0.123748

MSE validation: 0.1154

Train Epoch: 238 [0/2351 (0%)]	Loss: 0.108711

MSE validation: 0.1153

Train Epoch: 239 [0/2351 (0%)]	Loss: 0.118643

MSE validation: 0.1151

Train Epoch: 240 [0/2351 (0%)]	Loss: 0.106252

MSE validation: 0.1149

Train Epoch: 241 [0/2351 (0%)]	Loss: 0.153355

MSE validation: 0.1147

Train Epoch: 242 [0/2351 (0%)]	Loss: 0.115594

MSE validation: 0.1146

Train Epoch: 243 [0/2351 (0%)]	Loss: 0.132649

MSE validation: 0.1144

Train Epoch: 244 [0/2351 (0%)]	Loss: 0.097274

MSE validation: 0.1145

Train Epoch: 245 [0/2351 (0%)]	Loss: 0.114894

MSE validation: 0.1141

Train Epoch: 246 [0/2351 (0%)]	Loss: 0.117958

MSE validation: 0.1140

Train Epoch: 247 [0/2351 (0%)]	Loss: 0.100488

MSE validation: 0.1138

Train Epoch: 248 [0/2351 (0%)]	Loss: 0.117100

MSE validation: 0.1139

Train Epoch: 249 [0/2351 (0%)]	Loss: 0.107567

MSE validation: 0.1136

Train Epoch: 250 [0/2351 (0%)]	Loss: 0.111035

MSE validation: 0.1134

Train Epoch: 251 [0/2351 (0%)]	Loss: 0.108655

MSE validation: 0.1133

Train Epoch: 252 [0/2351 (0%)]	Loss: 0.094869

MSE validation: 0.1132

Train Epoch: 253 [0/2351 (0%)]	Loss: 0.109845

MSE validation: 0.1129

Train Epoch: 254 [0/2351 (0%)]	Loss: 0.104679

MSE validation: 0.1129

Train Epoch: 255 [0/2351 (0%)]	Loss: 0.106771

MSE validation: 0.1126

Train Epoch: 256 [0/2351 (0%)]	Loss: 0.102578

MSE validation: 0.1127

Train Epoch: 257 [0/2351 (0%)]	Loss: 0.114972

MSE validation: 0.1123

Train Epoch: 258 [0/2351 (0%)]	Loss: 0.112932

MSE validation: 0.1123

Train Epoch: 259 [0/2351 (0%)]	Loss: 0.112276

MSE validation: 0.1120

Train Epoch: 260 [0/2351 (0%)]	Loss: 0.119935

MSE validation: 0.1118

Train Epoch: 261 [0/2351 (0%)]	Loss: 0.119849

MSE validation: 0.1117

Train Epoch: 262 [0/2351 (0%)]	Loss: 0.101019

MSE validation: 0.1117

Train Epoch: 263 [0/2351 (0%)]	Loss: 0.109132

MSE validation: 0.1114

Train Epoch: 264 [0/2351 (0%)]	Loss: 0.100732

MSE validation: 0.1112

Train Epoch: 265 [0/2351 (0%)]	Loss: 0.110990

MSE validation: 0.1111

Train Epoch: 266 [0/2351 (0%)]	Loss: 0.128308

MSE validation: 0.1110

Train Epoch: 267 [0/2351 (0%)]	Loss: 0.101043

MSE validation: 0.1108

Train Epoch: 268 [0/2351 (0%)]	Loss: 0.097143

MSE validation: 0.1106

Train Epoch: 269 [0/2351 (0%)]	Loss: 0.100064

MSE validation: 0.1105

Train Epoch: 270 [0/2351 (0%)]	Loss: 0.093039

MSE validation: 0.1103

Train Epoch: 271 [0/2351 (0%)]	Loss: 0.098779

MSE validation: 0.1102

Train Epoch: 272 [0/2351 (0%)]	Loss: 0.105454

MSE validation: 0.1101

Train Epoch: 273 [0/2351 (0%)]	Loss: 0.102736

MSE validation: 0.1099

Train Epoch: 274 [0/2351 (0%)]	Loss: 0.113484

MSE validation: 0.1098

Train Epoch: 275 [0/2351 (0%)]	Loss: 0.091167

MSE validation: 0.1096

Train Epoch: 276 [0/2351 (0%)]	Loss: 0.140022

MSE validation: 0.1095

Train Epoch: 277 [0/2351 (0%)]	Loss: 0.100914

MSE validation: 0.1093

Train Epoch: 278 [0/2351 (0%)]	Loss: 0.098667

MSE validation: 0.1091

Train Epoch: 279 [0/2351 (0%)]	Loss: 0.113800

MSE validation: 0.1093

Train Epoch: 280 [0/2351 (0%)]	Loss: 0.088456

MSE validation: 0.1089

Train Epoch: 281 [0/2351 (0%)]	Loss: 0.112951

MSE validation: 0.1087

Train Epoch: 282 [0/2351 (0%)]	Loss: 0.107869

MSE validation: 0.1086

Train Epoch: 283 [0/2351 (0%)]	Loss: 0.079049
